export const GET_ALL_PATIENTS = "GET_ALL_PATIENTS";
export const GET_A_PATIENT_BY_ID = "GET_A_PATIENT_BY_ID";
export const GET_PATIENTS_BY_NAME = "GET_PATIENTS_BY_NAME";
export const CREATE_NEW_PATIENT = "CREATE_NEW_PATIENT";
export const UPDATE_PATIENT_INFO = "UPDATE_PATIENT_INFO";
export const DELETE_PATIENT_INFO = "DELETE_PATIENT_INFO";